const roomsData = [
  {
    roomId: "1",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "2",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "3",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "4",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "5",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "6",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "7",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "8",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "9",
    roomType: "single",
    maxGuests: 1,
    price: 500,
  },
  {
    roomId: "10",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "11",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "12",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "13",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "14",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "15",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "16",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "17",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "18",
    roomType: "double",
    maxGuests: 2,
    price: 1000,
  },
  {
    roomId: "19",
    roomType: "suite",
    maxGuests: 3,
    price: 1500,
  }, 
  {
    roomId: "20",
    roomType: "suite",
    maxGuests: 3,
    price: 1500,
    TableName: "roomsDb",
  },
];

module.exports = { roomsData };
